archives:
  - format: zip
    files:
      - "*.json"
release:
  mode: replace
  header: |
    ## Impartus video downloader release {{ .Tag }}
changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
